predicate/association in meta knowledge graph
biothings/biothings_explorer pull request #610
Opened 2023-04-05 01:51 UTC by rjawesome

https://github.com/biothings/BioThings_Explorer_TRAPI/issues/599, https://github.com/biothings/BioThings_Explorer_TRAPI/issues/595

Currently doesn't merge edges with same input/output/predicate but different qualfiers in the meta knowledge graph.
Association can be specified in the yaml through association_id property, ie.
```yml
...
outputs:
      - id: NCBIGene
        semantic: Gene
association_id:estToTest
...
```
Qualifiers are just read from the existing qualifiers in yaml.

2023-04-06 17:37 UTC, tokebe requested changes
So far so good, but a few notes:
- `qualifier_type_id` should have the `biolink:` prefix stripped and re-added to ensure it's present and non-duplicated
- applicable_values should have `biolink:` prefix stripped, and only added if the `qualifier_type_id` includes `"predicate"`

Regarding your question about `supportedLookups()`:

`supportedLookups()` should add the complete qualifier set from the given template (provided the template has qualifiers) to each supported lookup it generates. In `controllers/meta_knowledge_graph.js`, the step that calls `supportedLookups()` should use this new qualifier information alongside the subject/predicate/object to attempt to match to an existing edge. If it matches, add the knowledge type inferred to that edge, otherwise make a new edge with just knowledge type inferred and the information from the supported lookup.

2023-04-06 17:37 UTC, tokebe commented on src/controllers/meta_knowledge_graph.js
>        if (!predicates[input][output].includes(pred)) {
This check should be updated to ensure no duplicates are added

2023-04-06 17:47 UTC, rjawesome commented
@tokebe Can you give a sample template file. I don't see it in the bte trapi repo but maybe I'm missing it?

2023-04-06 17:52 UTC, tokebe commented
Follow the imports: `controllers/meta_knowledge_graphs.js` imports `supportedLookups()` from [`query_graph_handler`](https://github.com/biothings/bte_trapi_query_graph_handler/blob/380ee0691bd00a92605450aedb9528a13ed1fe11/src/index.js#L27), which imports it from [`query_graph_handler/src/inferred_mode/template_lookup.js`](https://github.com/biothings/bte_trapi_query_graph_handler/blob/380ee0691bd00a92605450aedb9528a13ed1fe11/src/inferred_mode/template_lookup.js#L54), which shows that templates are read from [`templateGroups.json`](https://github.com/biothings/bte_trapi_query_graph_handler/blob/main/data/templateGroups.json).

2023-04-06 18:08 UTC, rjawesome commented
Oh I was looking for the file in the wrong repo...

2023-04-08 00:42 UTC, rjawesome commented
Should be fixed, also a new PR on query graph handler

2023-04-11 03:57 UTC, colleenXu commented
Regarding `association` functionality...
* Could we put it into a separate PR / separate set of PRs? I'm thinking that we'll test this functionality later, when we put the info into the SmartAPI yamls
* could the SmartAPI yaml (x-bte operation) property name be changed from "association_id" -> "biolink_association_type"?
* In the SmartAPI yaml, the property's value will probably be just the term like [EntityToDiseaseAssociation](https://biolink.github.io/biolink-model/docs/EntityToDiseaseAssociation.html). But in the endpoint response, we will want this to have the biolink-prefix (`"association": "biolink:EntityToDiseaseAssociation"`)

2023-04-11 04:23 UTC, colleenXu commented
@tokebe 

I have a question specific to the `v1/meta_knowledge_graph` response. When a MetaEdge can be done as `lookup` or creative-mode....did we want to have one operation with `"knowledge_types": ["inferred", "lookup"]` or two? 

With the current PR code, two separate MetaEdges are made. I saw these two:

```
        {
            "subject": "biolink:SmallMolecule",
            "predicate": "biolink:treats",
            "object": "biolink:Disease",
            "knowledge_types": [
                "inferred"
            ]
        },


        {
            "subject": "biolink:SmallMolecule",
            "predicate": "biolink:treats",
            "object": "biolink:Disease",
            "knowledge_types": [
                "inferred"
            ]
        },
```

2023-04-11 04:23 UTC, colleenXu commented
@tokebe @rjawesome 

Regarding `association` functionality...
* Could we put it into a separate PR / separate set of PRs? I'm thinking that we'll test this functionality later, when we put the info into the SmartAPI yamls
* could the SmartAPI yaml (x-bte operation) property name be changed from "association_id" -> "biolink_association_type"?
* In the SmartAPI yaml, the property's value will probably be just the term like [EntityToDiseaseAssociation](https://biolink.github.io/biolink-model/docs/EntityToDiseaseAssociation.html). But in the endpoint response, we will want this to have the biolink-prefix (`"association": "biolink:EntityToDiseaseAssociation"`)

2023-04-11 04:32 UTC, colleenXu commented
And I changed the title because I assumed we meant "qualifiers". 

I'm done with my quick testing of the "qualifiers functionality" for https://github.com/biothings/BioThings_Explorer_TRAPI/issues/595. I posed my two questions / chunks of feedback above, and I guess we'll wait to hear about the "qualifier-set merging" from the TRAPI team / Translator (and we'll track that discussion in the issue). 

It looks great overall!

2023-04-12 21:00 UTC, rjawesome commented
Association has been moved into its own PR. Will address Colleen's comments in that PR

2023-04-13 20:43 UTC, tokebe commented
> @tokebe
> 
> I have a question specific to the `v1/meta_knowledge_graph` response. When a MetaEdge can be done as `lookup` or creative-mode....did we want to have one operation with `"knowledge_types": ["inferred", "lookup"]` or two?
> 
> With the current PR code, two separate MetaEdges are made. I saw these two:
> 
> ```
>         {
>             "subject": "biolink:SmallMolecule",
>             "predicate": "biolink:treats",
>             "object": "biolink:Disease",
>             "knowledge_types": [
>                 "lookup"
>             ]
>         },
> 
> 
>         {
>             "subject": "biolink:SmallMolecule",
>             "predicate": "biolink:treats",
>             "object": "biolink:Disease",
>             "knowledge_types": [
>                 "inferred"
>             ]
>         },
> ```

We want edges that are exactly the same other than `knowledge_types` to be merged, so it's one edge with `"knowledge_types": ["inferred", "lookup"]`.

2023-04-13 21:46 UTC, rjawesome commented
Should be fixed

2023-04-14 15:05 UTC, tokebe commented
Fix currently has inferred duplicating on some edges, like below:

```json
{
      "subject": "biolink:SmallMolecule",
      "predicate": "biolink:affects",
      "object": "biolink:Gene",
      "qualifiers": [
        {
          "qualifier_type_id": "biolink:causal_mechanism_qualifier",
          "applicable_values": [
            "inverse_agonism"
          ]
        },
        {
          "qualifier_type_id": "biolink:object_aspect_qualifier",
          "applicable_values": [
            "activity"
          ]
        },
        {
          "qualifier_type_id": "biolink:object_direction_qualifier",
          "applicable_values": [
            "decreased"
          ]
        },
        {
          "qualifier_type_id": "biolink:qualified_predicate",
          "applicable_values": [
            "biolink:causes"
          ]
        }
      ],
      "knowledge_types": [
        "lookup",
        "inferred",
        "inferred"
      ]
    },
```

2023-04-14 15:07 UTC, tokebe commented
(Also, I merged the latest from main, you'll have to update your workspace by cloning this repo fresh and using `npm run setup`)

2023-04-14 22:02 UTC, rjawesome commented
Shoudl be fixed

2023-04-15 05:43 UTC, colleenXu commented
Hmmm....What is shown [above](https://github.com/biothings/biothings_explorer/pull/610#issuecomment-1508735715) is actually "incorrect" because we wouldn't actually run creative-mode on a QEdge if all those qualifiers were specified as constraints on that QEdge. 

I think some logic may be needed to figure out when a `lookup` TRAPI MetaEdge should have the `inferred` string added to `knowledge_types` (aka "merging"). Maybe the logic is similar to what's done to match a QGraph QEdge to creative-mode templates...

Some thoughts I have: 
* if a `lookup` edge has more qualifiers specified (larger set of type_ids), then it is representing MORE SPECIFIC stuff than the creative-mode template and creative-mode won't run. So we shouldn't add the `inferred` string...
* If the `lookup` edge had the exact same set of qualifier type_ids/values as a creative-mode template (and the subject/predicate/object matches too), then we want to add the `inferred` string
    * I doubt that we have a `lookup` edge for `SmallMolecule-affects-Gene` with the exact qualifier set `increased activity_or_abundance`. But if we do, then we'd want to add the `inferred` string. 
    * If we don't have that `lookup` edge, we'll make an `inferred`-only TRAPI MetaEdge...
* but we also currently have some ambiguity in our creative-mode behavior: creative-mode will happen if the `inferred` QEdge's qualifier set is more general. Do we want to add the `inferred` string in these situations?
    *  For example, I know we have a `lookup` edge where `SmallMolecule-affects-Gene` with NO qualifiers. We could decide to add the `inferred` string there, since creative-mode will run if an `inferred` QEdge like that was provided...
    * Another example: I doubt that we have a `lookup` edge SmallMolecule-affects-Gene` with the exact qualifier set `increased`. But if we did, we could decide to add the `inferred` string there since creative mode would run...
    * I'm not sure we ever got clarification from the rest of Translator on whether this ambiguity in behavior was okay. We discussed it as "point 2" earlier this year here: my [question](https://github.com/biothings/biothings_explorer/issues/532#issuecomment-1378322378), Jackson [reply](https://github.com/biothings/biothings_explorer/issues/532#issuecomment-1378953156), Andrew [reply](https://github.com/biothings/biothings_explorer/issues/532#issuecomment-1379094937)

2023-04-17 15:02 UTC, tokebe commented
I'm not convinced this logic is necessary... based on the way the poll is going, it's looking like Translator want the more general "all possible qualifiers" option, in which case such ambiguity is expected. It wouldn't be read as "we support creative mode on this edge with these qualifiers", so much as "we support creative mode on this edge with some subset of these qualifiers" and then we have no duty to be more clear.

2023-04-27 21:14 UTC, tokebe commented
Looks like this is almost ready to go -- I'm noticing a couple cases of duplicate "inferred" in some of the metaEdges, however:

```
{
      "subject": "biolink:ComplexMolecularMixture",
      "predicate": "biolink:affects",
      "object": "biolink:Protein",
      "qualifiers": [
        {
          "qualifier_type_id": "biolink:object_aspect_qualifier",
          "applicable_values": ["activity_or_abundance"]
        },
        {
          "qualifier_type_id": "biolink:object_direction_qualifier",
          "applicable_values": ["increased", "decreased"]
        }
      ],
      "knowledge_types": ["inferred", "inferred"]
    }
```

2023-05-22 17:16 UTC, tokebe approved these changes

2023-05-22 17:28 UTC, merged